### PR TITLE
Upgrade to elm 0.19

### PR DESCRIPTION
**Pull request by andys8**
Updates the api and the example. A change in the elm api for [`style`](https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md#functions-changed) leads to a change to return `Attribute msg` instead of `(String, String)`. The example and the documentation is adapted.

### CODE REVIEW

**Comment by andys8** [comment]
Hey @etaque, did you forget merging this PR? Because you already merged the documentation referring to these changes https://github.com/etaque/elm-transit/pull/11 ;)

Any open questions?

**Comment by andys8** [comment]
Ping ;)

**Comment by etaque** [comment]
Done and published, @andys8. Sorry for the long wait!

**Comment by andys8** [comment]
Thank you

**Pull request merged**
